In [1]:
import numpy as np
import numpy.linalg as lin

In [29]:
a = np.array([[1,1],[2,1]])
print(a)
print('\n')

print(f"size of a is {a.shape}")
print('\n')
print(lin.inv(a))
print('\n')

# y는 그냥 벡터, NOT 행렬
y = np.array([2,4])
print(f"shape of y is {y.shape}")
print('\n')

# y1은 row벡터, y_2는 column벡터
y_1 = np.array([[2,4]])
y_2 = np.array([[2], [4]])
print(f"y_1 = {y_1}")
print(f"y_2 = {y_2}")
print('\n')

# y_는 column벡터
y_ = np.array([2,4]).reshape(2,1)
print(y_)


[[1 1]
 [2 1]]


size of a is (2, 2)


[[-1.  1.]
 [ 2. -1.]]


shape of y is (2,)


y_1 = [[2 4]]
y_2 = [[2]
 [4]]


[[2]
 [4]]


In [31]:
w1 = lin.inv(a) * y
print(w1)
print('\n')

w2 = lin.inv(a) * y_
print(w2)
print('\n')

# 이게 진짜 행렬곱
w3 = np.matmul(lin.inv(a), y)
print(w3)

[[-2.  4.]
 [ 4. -4.]]


[[-2.  2.]
 [ 8. -4.]]


[2. 0.]


In [32]:
# y = wx + b
y = w[0,0]*np.array([-3, -2, -1, 0, 1, 2, 3]) + w[1,0]
print(y)
# np.matmul(w, np.array([1,1]))

[14. 12. 10.  8.  6.  4.  2.]


In [2]:
x_ = np.array([[-1,1], [0,1], [1,1], [2,1]])
np.matmul(x_,w)

NameError: name 'w' is not defined